apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"run":"ddns"},"name":"ddns","namespace":"default"},"spec":{"ports":[{"name":"port-1","port":53,"protocol":"UDP","targetPort":53},{"name":"port-2","port":533,"protocol":"UDP","targetPort":533}],"selector":{"run":"ddns"},"sessionAffinity":"None","type":"NodePort"}}
  creationTimestamp: null
  labels:
    run: ddns
  name: ddns
  selfLink: /api/v1/namespaces/default/services/ddns
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: port-1
    port: 53
    protocol: UDP
    targetPort: 53
  - name: port-2
    port: 533
    protocol: UDP
    targetPort: 533
  selector:
    run: ddns
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
