---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  generation: 1
  labels:
    run: ddns
  name: ddns
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: ddns
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ddns
    spec:
      containers:
      - image: registr.dnion.com:5000/ddns:v1
        imagePullPolicy: IfNotPresent
        name: ddns
        resources:
          requests:
            cpu: "200m"
            memory: "1024Mi"
          limits:
            cpu: "2000m"
            memory: "4096Mi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - name: basesvcm
          containerPort: 53
          protocol: UDP
          #hostPort: 53
        - name: backupsvcm
          protocol: TCP
          containerPort: 9153
          #hostPort: 9153
#        livenessProbe:
#          failureThreshold: 3
#          httpGet:
#            path: /httpdns/nxnop0702.flxdns.com?subclient=60.220.0.0
#            port: 9153
#            scheme: HTTP
#          initialDelaySeconds: 10
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 1 
#
#        livenessProbe:
#          tcpSocket:
#            port: 9153
#          initialDelaySeconds: 15
#          periodSeconds: 40
#        readinessProbe:
#          tcpSocket:
#            port: 9153
#          initialDelaySeconds: 5
#          periodSeconds: 20
#
#        readinessProbe:
#          failureThreshold: 3
#          httpGet:
#            path: /healthz
#            port: 10254
#            scheme: HTTP
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ddns
  name: ddns
spec:
  externalTrafficPolicy: Local
  ports:
  - name: basesvcm
    port: 53
    protocol: UDP
    targetPort: 53
  - name: backupsvcm
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    run: ddns
  sessionAffinity: None
  type: NodePort
