apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ddns
  name: ddns
  selfLink: /api/v1/namespaces/default/services/ddns
spec:
  ports:
  - port: 53
    protocol: TCP
    targetPort: 53
  selector:
    run: ddns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
