---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: ddnsingress
  name: ddnsingress
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/ddns
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: ddnsingress
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ddnsingress
    spec:
      containers:
      - image: cs9.dnion.com:5000/ddns:1
        imagePullPolicy: IfNotPresent
        name: ddns
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---


apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ddnsingress
  name: ddnsingress
  selfLink: /api/v1/namespaces/default/services/ddns2
spec:
  ports:
  - name: port-1
    port: 53
    protocol: UDP
    targetPort: 53
  - name: port-2
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    run: ddnsingress
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
