apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: ddns
  name: ddns
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/ddns
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: ddns
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ddns
    spec:
      containers:
      - image: cs9.dnion.com:5000/ddns:1
        imagePullPolicy: IfNotPresent
        name: ddns
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ddns
  name: metalddns
  selfLink: /api/v1/namespaces/default/services/metalddns
spec:
  ports:
  - name: basesvcm
    port: 53
    protocol: UDP
    targetPort: 53
  - name: backupsvcm
    port: 533
    protocol: UDP
    targetPort: 533
  selector:
    run: ddns
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
