apiVersion: v1
kind: Service
metadata:
  name: ddns
  namespace: default
spec:
  ports:
  - name: base
    port: 53
    protocol: UDP
    targetPort: 53
  - name: up
    port: 533
    protocol: UDP
    targetPort: 533
  selector:
    run: ddns
  type: NodePort
