apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"run":"ddns"},"name":"ddns","namespace":"default"},"spec":{"externalIPs":["183.131.215.252"],"ports":[{"name":"basesvcm","port":53,"protocol":"UDP","targetPort":53},{"name":"backupsvcm","port":9153,"protocol":"TCP","targetPort":9153}],"selector":{"run":"ddns"},"sessionAffinity":"None"}}
  creationTimestamp: null
  labels:
    run: ddns
  name: ddns
  selfLink: /api/v1/namespaces/default/services/ddns
spec:
  externalTrafficPolicy: Local
  ports:
  - name: basesvcm
    port: 53
    protocol: UDP
    targetPort: 53
  - name: backupsvcm
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    run: ddns
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
