apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ddns
  name: ddns
  selfLink: /api/v1/namespaces/default/services/ddns
spec:
  ports:
  - name: basesvc
    port: 53
    protocol: UDP
    targetPort: 53
  - name: backupsvc
    port: 533
    protocol: UDP
    targetPort: 533
  selector:
    run: ddns
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
