apiVersion: v1
items:
- apiVersion: autoscaling/v2beta1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: 2018-07-03T08:26:35Z
    name: ddns
    namespace: default
    resourceVersion: "13086"
    selfLink: /apis/autoscaling/v2beta1/namespaces/default/horizontalpodautoscalers/ddns
    uid: cc5be133-7e9a-11e8-933d-70e2840fa859
  spec:
    maxReplicas: 10
    metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 50
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: ddns
  status:
    conditions:
    - lastTransitionTime: 2018-07-03T08:27:05Z
      message: the HPA controller was able to get the target's current scale
      reason: SucceededGetScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: 2018-07-03T08:27:05Z
      message: 'the HPA was unable to compute the replica count: unable to get metrics
        for resource cpu: unable to fetch metrics from resource metrics API: the server
        could not find the requested resource (get pods.metrics.k8s.io)'
      reason: FailedGetResourceMetric
      status: "False"
      type: ScalingActive
    currentMetrics: null
    currentReplicas: 1
    desiredReplicas: 0
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
