apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-udpbind
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - name: basesvcm
    port: 53
    protocol: UDP
    targetPort: 53
  - name: backupsvcm
    port: 533
    protocol: UDP
    targetPort: 533
  selector:
    app: ingress-nginx
