---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  name: ddnsm2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: ddnsm2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ddnsm2
    spec:
      containers:
      - image: registr.dnion.com:5000/ddns:v1
        imagePullPolicy: IfNotPresent
        name: ddnsm2
        ports:
        - containerPort: 53
          name: basesvcm
          protocol: UDP
        - containerPort: 9153
          name: backupsvcm
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /httpdns/nxnop0702.flxdns.com?subclient=60.220.0.0
            port: 9153
            scheme: HTTP
          initialDelaySeconds: 70
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1 
        readinessProbe:
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /httpdns/nxnop0702.flxdns.com?subclient=60.220.0.0
            port: 9153
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1 
#
#        livenessProbe:
#          tcpSocket:
#            port: 9153
#          initialDelaySeconds: 15
#          periodSeconds: 40
#        readinessProbe:
#          tcpSocket:
#            port: 9153
#          initialDelaySeconds: 5
#          periodSeconds: 20
#---
#
#        readinessProbe:
#          failureThreshold: 3
#          httpGet:
#            path: /healthz
#            port: 10254
#            scheme: HTTP
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 1
        resources:
          limits:
            cpu: "24"
            memory: 64Gi
          requests:
            cpu: 1200m
            memory: 5Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
